server:
  port: 8080
  servlet:
     context-path: /avakids
spring:
  application:
    name: avakids-backend
  datasource:
    url: ${DB_URL_MYSQL:jdbc:mysql://localhost:3306/avakids_5?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/avakids}
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  spring.task.scheduling.time-zone: Asia/Ho_Chi_Minh
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  messages:
    encoding: UTF-8

jwt:
  signerKey: ${JWT_SIGNER_KEY:bvkfSG5tgcc6kHcMWz6VpgyEjCmg16w8EzZv5mPs3KT4Tt1lS3AhkkOBE3oabTJ8}
  vaild-duration: 18000
  refresh-duration: 8640000
app:
  file:
    upload-dir: uploads  # Thư mục gốc để lưu file
    max-size: 5242880    # 5MB in bytes
    max-size-img: 2097152    # 2MB in bytes
  firebase-configuration-file: avakis-6bdad-firebase-adminsdk-fbsvc-f62bf64a7b.json
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dvszcmofn}
  api-key: ${CLOUDINARY_API_KEY:827484186465121}
  api-secret: ${CLOUDINARY_API_SECRET:3MzIIBiE8DcAMNf7eirEhg8uAKw}
